# Generated by Django 5.2.8 on 2026-02-04 18:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_code', models.CharField(help_text='Code of the metric to analyze', max_length=100)),
                ('chart_type', models.CharField(help_text='Type of chart to generate', max_length=50)),
                ('config', models.JSONField(default=dict, help_text="Configuration: {\n            'x_axis': 'column_name',\n            'y_axis': 'column_name',\n            'time_aggregation': 'D/W/M/Y',\n            'aggregation': 'sum/mean/median',\n            'filters': {...},\n            'custom_params': {...}\n        }")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code identifier', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='Category: timeseries, distribution, correlation, etc.', max_length=50)),
                ('default_chart_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('scatter', 'Scatter Plot'), ('histogram', 'Histogram'), ('pie', 'Pie Chart'), ('heatmap', 'Heatmap'), ('box', 'Box Plot'), ('area', 'Area Chart')], max_length=50)),
                ('supported_chart_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='List of supported chart types for this metric', size=None)),
                ('required_columns', models.JSONField(help_text="List of required column patterns: ['Creation_Date', '#Commits']")),
                ('supports_time_aggregation', models.BooleanField(default=False)),
                ('supports_custom_axes', models.BooleanField(default=False)),
                ('default_aggregation', models.CharField(blank=True, choices=[('sum', 'Sum'), ('mean', 'Mean'), ('median', 'Median'), ('count', 'Count'), ('min', 'Min'), ('max', 'Max'), ('std', 'Standard Deviation')], max_length=20, null=True)),
                ('analysis_function', models.CharField(help_text='Name of the function in analysis_functions.py', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metric_definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_data', models.JSONField(help_text='Data structure for interactive charts (plotly/recharts format)')),
                ('chart_image', models.TextField(blank=True, help_text='Base64 encoded matplotlib image', null=True)),
                ('statistics', models.JSONField(blank=True, help_text='Additional statistical information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analytics.analysis')),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('repository_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('platform', models.CharField(default='gitlab', max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('rows_count', models.IntegerField(default=0)),
                ('columns_count', models.IntegerField(default=0)),
                ('columns_metadata', models.JSONField(default=dict, help_text='Metadata about columns: {column_name: {type: str, unique_values: int, ...}}')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['workspace_id', 'repository_id'], name='datasets_workspa_a78d5a_idx'), models.Index(fields=['-uploaded_at'], name='datasets_uploade_c9b9eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_analyses', models.IntegerField(default=0)),
                ('completed_analyses', models.IntegerField(default=0)),
                ('failed_analyses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_batches', to='analytics.dataset')),
            ],
            options={
                'db_table': 'analysis_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics.dataset'),
        ),
        migrations.CreateModel(
            name='BatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_memberships', to='analytics.analysis')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_analyses', to='analytics.analysisbatch')),
            ],
            options={
                'db_table': 'batch_analyses',
                'ordering': ['order'],
                'unique_together': {('batch', 'analysis')},
            },
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status'], name='analyses_status_a2cfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['metric_code'], name='analyses_metric__9410ea_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['-created_at'], name='analyses_created_40cfc0_idx'),
        ),
    ]
