# Generated by Django 5.2.8 on 2026-01-15 02:50

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workspace_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "repository_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("platform", models.CharField(default="gitlab", max_length=50)),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("rows_count", models.IntegerField(default=0)),
                ("columns_count", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "datasets",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "repository_id"],
                        name="datasets_workspa_a78d5a_idx",
                    ),
                    models.Index(
                        fields=["-uploaded_at"], name="datasets_uploade_c9b9eb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_charts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        help_text="List of requested chart types",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="analytics.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chart_type", models.CharField(max_length=100)),
                ("chart_image", models.TextField(help_text="Base64 encoded image")),
                (
                    "chart_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data or statistics for the chart",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analytics.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_results",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "chart_type"],
                        name="analysis_re_analysi_2a70e1_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(fields=["status"], name="analyses_status_a2cfc9_idx"),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["-created_at"], name="analyses_created_40cfc0_idx"
            ),
        ),
    ]
