/**
 * DSLPreview
 * ==========
 * Displays the Analysis DSL JSON document generated by the LLM.
 *
 * Shows:
 *  - Syntax-highlighted JSON (via a <pre> block + minimal CSS classes)
 *  - A short human-readable summary of the DSL intent
 *  - A "Run" button and an "Edit" toggle to modify the JSON before execution
 *  - Validation errors if the DSL is malformed
 */
import React, { useState, useCallback } from "react";

/* ------------------------------------------------------------------ */
/*  Human-readable DSL summary                                          */
/* ------------------------------------------------------------------ */
function describeDsl(dsl) {
  if (!dsl || typeof dsl !== "object") return "No DSL";

  const parts = [];

  if (dsl.select?.metric) {
    const agg = dsl.select.aggregation || "avg";
    parts.push(`${agg.toUpperCase()} of ${dsl.select.metric}`);
  } else if (dsl.series?.length) {
    parts.push(`${dsl.series.length} metric series`);
  } else if (dsl.select?.metrics?.length) {
    parts.push(`Correlation heatmap (${dsl.select.metrics.length} metrics)`);
  }

  if (dsl.group_by?.column) {
    parts.push(`grouped by ${dsl.group_by.column}`);
  } else if (dsl.group_by?.time) {
    const t = dsl.group_by.time;
    parts.push(`by ${t.period || "month"}`);
  }

  if (dsl.filters?.length) {
    parts.push(`${dsl.filters.length} filter(s)`);
  }

  if (dsl.limit) {
    parts.push(`top ${dsl.limit}`);
  }

  return parts.length ? parts.join(", ") : `${dsl.chart?.type || "chart"} analysis`;
}

/* ------------------------------------------------------------------ */
/*  Syntax highlight (no dependency – pure CSS classes)                 */
/* ------------------------------------------------------------------ */
function JsonHighlight({ json }) {
  const text = JSON.stringify(json, null, 2);
  return (
    <pre className="dsl-preview__code">
      {text}
    </pre>
  );
}

/* ------------------------------------------------------------------ */
/*  Main component                                                      */
/* ------------------------------------------------------------------ */
export default function DSLPreview({
  dsl,
  isLoading = false,
  errors = [],
  onRun,
  onEdit,
  className = "",
}) {
  const [editMode, setEditMode] = useState(false);
  const [editedJson, setEditedJson] = useState("");
  const [parseError, setParseError] = useState(null);

  const handleEditToggle = useCallback(() => {
    if (!editMode) {
      setEditedJson(JSON.stringify(dsl, null, 2));
      setParseError(null);
    }
    setEditMode((v) => !v);
  }, [editMode, dsl]);

  const handleEditChange = useCallback((e) => {
    setEditedJson(e.target.value);
    setParseError(null);
  }, []);

  const handleRunEdited = useCallback(() => {
    try {
      const parsed = JSON.parse(editedJson);
      setParseError(null);
      if (onEdit) onEdit(parsed);
    } catch (err) {
      setParseError(`Invalid JSON: ${err.message}`);
    }
  }, [editedJson, onEdit]);

  if (isLoading) {
    return (
      <div className={`dsl-preview dsl-preview--loading ${className}`}>
        <div className="dsl-preview__spinner" />
        <span className="dsl-preview__loading-text">Generating analysis plan…</span>
      </div>
    );
  }

  if (!dsl) return null;

  const hasErrors = errors.length > 0;
  const chartType = dsl.chart?.type || "—";
  const summary = describeDsl(dsl);

  return (
    <div className={`dsl-preview ${hasErrors ? "dsl-preview--error" : ""} ${className}`}>

      {/* Header */}
      <div className="dsl-preview__header">
        <div className="dsl-preview__meta">
          <span className="dsl-preview__chip dsl-preview__chip--type">{chartType}</span>
          <span className="dsl-preview__summary">{summary}</span>
        </div>
        <div className="dsl-preview__actions">
          {!hasErrors && (
            <button
              className="dsl-preview__btn dsl-preview__btn--edit"
              onClick={handleEditToggle}
              type="button"
            >
              {editMode ? "Cancel" : "Edit DSL"}
            </button>
          )}
          {!editMode && !hasErrors && onRun && (
            <button
              className="dsl-preview__btn dsl-preview__btn--run"
              onClick={() => onRun(dsl)}
              type="button"
            >
              Run Analysis
            </button>
          )}
          {editMode && (
            <button
              className="dsl-preview__btn dsl-preview__btn--run"
              onClick={handleRunEdited}
              type="button"
            >
              Run Edited DSL
            </button>
          )}
        </div>
      </div>

      {/* Validation errors */}
      {hasErrors && (
        <div className="dsl-preview__errors">
          <strong>DSL Errors</strong>
          <ul>
            {errors.map((e, i) => <li key={i}>{e}</li>)}
          </ul>
        </div>
      )}

      {/* JSON preview / editor */}
      <div className="dsl-preview__body">
        {editMode ? (
          <>
            <textarea
              className="dsl-preview__editor"
              value={editedJson}
              onChange={handleEditChange}
              rows={Math.min(30, editedJson.split("\n").length + 2)}
              spellCheck={false}
            />
            {parseError && (
              <p className="dsl-preview__parse-error">{parseError}</p>
            )}
          </>
        ) : (
          <JsonHighlight json={dsl} />
        )}
      </div>

    </div>
  );
}
