# Generated by Django 5.2.8 on 2026-06-24 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualitativeDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_id', models.IntegerField(help_text='Source collection id')),
                ('user_id', models.IntegerField()),
                ('workspace_id', models.IntegerField(blank=True, null=True)),
                ('repository_full_name', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=20)),
                ('qualitative_data_filename', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stats', models.JSONField(default=dict, help_text='Summary stats for the dashboard header/charts')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualitative_datasets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='qualitative_user_id_6e78b2_idx'), models.Index(fields=['collection_id'], name='qualitative_collect_c20a96_idx'), models.Index(fields=['status'], name='qualitative_status_a0b93b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('comment_type', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('author_is_bot', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_human', models.BooleanField(default=True)),
                ('body', models.TextField(blank=True, default='')),
                ('path', models.TextField(blank=True, default='')),
                ('line', models.IntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, default='', max_length=10)),
                ('diff_hunk', models.TextField(blank=True, default='')),
                ('reply_to_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('review_number', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(blank=True, null=True)),
                ('got_reply', models.BooleanField(default=False)),
                ('code_changed_after', models.BooleanField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quality.qualitativedataset')),
            ],
            options={
                'db_table': 'qualitative_comments',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='quality.comment')),
            ],
            options={
                'db_table': 'qualitative_reactions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='PR number / MR iid')),
                ('title', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('reviewers', models.JSONField(default=list)),
                ('state', models.CharField(blank=True, default='', max_length=40)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('additions', models.IntegerField(blank=True, null=True)),
                ('deletions', models.IntegerField(blank=True, null=True)),
                ('changed_files', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quality.qualitativedataset')),
            ],
            options={
                'db_table': 'qualitative_reviews',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quality.review'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('thread_type', models.CharField(choices=[('general', 'General'), ('inline', 'Inline'), ('review_summary', 'Review summary')], max_length=20)),
                ('path', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(blank=True, null=True)),
                ('is_outdated', models.BooleanField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='quality.qualitativedataset')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='quality.review')),
            ],
            options={
                'db_table': 'qualitative_threads',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quality.thread'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('comment_count', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quality.qualitativedataset')),
            ],
            options={
                'db_table': 'qualitative_participants',
                'unique_together': {('dataset', 'login')},
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['dataset', 'number'], name='qualitative_dataset_1a8037_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['dataset', 'thread_type'], name='qualitative_dataset_c9c69b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['dataset', 'comment_type'], name='qualitative_dataset_ddd30a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['dataset', 'author'], name='qualitative_dataset_e719ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['dataset', 'is_human'], name='qualitative_dataset_d98d03_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['dataset', 'created_at'], name='qualitative_dataset_cfec95_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['dataset', 'review_number'], name='qualitative_dataset_0aa5a6_idx'),
        ),
    ]
