# Generated by Django 5.2.8 on 2026-06-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_role',
            field=models.CharField(default='reviewer', max_length=10),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['dataset', 'author_role'], name='qualitative_dataset_080657_idx'),
        ),
    ]
