# Generated by Django 5.2.8 on 2026-06-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_comment_author_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('general', 'General'), ('inline', 'Inline'), ('review_summary', 'Review summary'), ('commit_comment', 'Commit comment')], max_length=20),
        ),
    ]
