# Generated by Django 5.2.8 on 2025-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitlab_self', 'GitLab Self-Hosted')], max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('token_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config_workspaces',
                'ordering': ['-created_at'],
            },
        ),
    ]
