# Generated by Django 5.2.8 on 2025-12-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(help_text='User ID from API Gateway')),
                ('workspace_id', models.IntegerField(help_text='Workspace ID from Configuration Service')),
                ('repository_id', models.IntegerField(help_text='Repository ID from Configuration Service')),
                ('repository_name', models.CharField(max_length=255)),
                ('repository_full_name', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=20)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('default_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='Branch to collect data from', max_length=255, null=True)),
                ('token_encrypted', models.TextField(help_text='Encrypted access token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_metrics', models.JSONField(default=list, help_text='List of metrics to collect')),
                ('filters', models.JSONField(default=dict, help_text='Collection filters')),
                ('total_items', models.IntegerField(default=0)),
                ('collected_items', models.IntegerField(default=0)),
                ('stats', models.JSONField(default=dict, help_text='Collection statistics (commits_count, comments_count, etc.)')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('collection_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='collected_data', serialize=False, to='collectors.collectionplan')),
                ('raw_data', models.JSONField(help_text='All collected data organized by metric type: {pull_requests: [...], commits: [...], etc.}')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collected_data',
            },
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['user', 'repository_id'], name='collection__user_a40744_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['status'], name='collection__status_e2d3c9_idx'),
        ),
    ]
