# Generated by Django 5.2.8 on 2025-12-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(help_text='User ID from API Gateway')),
                ('workspace_id', models.IntegerField(help_text='Workspace ID from Configuration Service')),
                ('repository_id', models.IntegerField(help_text='Repository ID from Configuration Service')),
                ('repository_name', models.CharField(max_length=255)),
                ('repository_full_name', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_metrics', models.JSONField(blank=True, help_text='List of metrics to collect', null=True)),
                ('filters', models.JSONField(blank=True, help_text='Collection filters', null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('collected_items', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
