# Generated by Django 5.2.8 on 2025-12-06 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionplan',
            name='default_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='token_encrypted',
            field=models.TextField(default=None, help_text='Encrypted access token'),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='filters',
            field=models.JSONField(default=dict, help_text='Collection filters'),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='selected_metrics',
            field=models.JSONField(default=list, help_text='List of metrics to collect'),
        ),
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(help_text='Type of metric (pull_requests, commits, issues, etc.)', max_length=50)),
                ('raw_data', models.JSONField(help_text='Raw data from API')),
                ('external_id', models.CharField(help_text='ID from GitHub/GitLab API', max_length=100)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('collection_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_data', to='collectors.collectionplan')),
            ],
            options={
                'db_table': 'collected_data',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['collection_plan', 'metric_type'], name='collected_d_collect_63c0ca_idx'), models.Index(fields=['external_id'], name='collected_d_externa_5ca0e1_idx')],
                'unique_together': {('collection_plan', 'metric_type', 'external_id')},
            },
        ),
    ]
