# Generated by Django 5.2.8 on 2025-12-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_rename_cleaning_to_cleaneddata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cleaneddata',
            new_name='cleaned_dat_collect_2a8a5c_idx',
            old_name='cleanings_collect_idx',
        ),
        migrations.AlterField(
            model_name='cleaneddata',
            name='collection',
            field=models.ForeignKey(help_text='The collection this cleaned data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_data', to='collectors.collection'),
        ),
    ]
