# Generated by Django 5.2.8 on 2026-04-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0009_collection_is_total_approximate'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='save_batch_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of items to collect before saving to MinIO (1-100)'),
        ),
    ]
