# Backward-compatibility shim — do not add logic here.
from analytics.api.views import (  # noqa: F401
    DatasetListView,
    DatasetUploadView,
    DatasetDetailView,
    DatasetColumnsView,
    DatasetPreviewView,
    DatasetAvailableMetricsView,
    DatasetCompatibleAxesView,
    DatasetSummaryView,
    MetricListView,
    MetricCategoriesView,
    MetricByCategoryView,
    MetricDetailView,
    GenerateChartView,
    AnalysisListView,
    AnalysisBulkCreateView,
    AnalysisDetailView,
    AnalysisResultView,
    AnalysisRetryView,
    AnalysisHistoryView,
)
__all__ = [
    "DatasetListView", "DatasetUploadView", "DatasetDetailView",
    "DatasetColumnsView", "DatasetPreviewView", "DatasetAvailableMetricsView",
    "DatasetCompatibleAxesView", "DatasetSummaryView",
    "MetricListView", "MetricCategoriesView", "MetricByCategoryView", "MetricDetailView",
    "GenerateChartView",
    "AnalysisListView", "AnalysisBulkCreateView", "AnalysisDetailView",
    "AnalysisResultView", "AnalysisRetryView", "AnalysisHistoryView",
]
